export const RECEIVE_NOTIFICATION = "RECEIVE_NOTIFICATION";
export const SEND_NOTIFICATION_REQUESTED = "SEND_NOTIFICATION_REQUESTED";
export const SEND_NOTIFICATION_FAILED = "SEND_NOTIFICATION_FAILED";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
