version: '3.7'
services:
  gin-web-site:
    build: ./project
    restart: always
    depends_on:
      - postgresql
      - redis
    links:
      - postgresql
      - redis
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      mode: replicated
      replicas: 3

  postgresql:
    image: "postgres:latest"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user_go
      POSTGRES_DB: mydb
    expose:
      - "5432"

  redis:
    image: "redis:latest"
    restart: always
    deploy:
      mode: replicated
      replicas: 3

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - gin-web-site
