version: '3.7'
services:
  gin-web-site:
    build: ./project
    restart: always
    depends_on:
      - postgresql
      - redis
    links:
      - postgresql
      - redis
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.basic.frontend.rule=Host:localhost"
      - "traefik.basic.port=8000"
      - "traefik.websocket.frontend.rule=Host:127.0.0.1"
      - "traefik.websocket.port=8000" # forward request to port 8000 on container

  postgresql:
    image: "postgres:alpine"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user_go
      POSTGRES_DB: mydb
    expose:
      - "5432"
    deploy:
      mode: replicated
      replicas: 3

  redis:
    image: "redis:alpine"
    container_name: redis_master
    restart: always
    expose:
      - "6379"
    networks:
      - redis-replication
      - default

  redis-slave:
    image: "redis:alpine"
    container_name: slave
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis 6379
    depends_on:
      - redis
    networks:
      - redis-replication
      - default

  reverse-proxy:
    image: traefik:latest
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  redis-replication:
    driver: bridge
