version: "3.7"
services:
  web-server:
    build:
      context: ../project
      dockerfile: dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 3
    env_file:
     - ../project/.env
