version: "3.7"
services:
  reverse-proxy:
    image: traefik:latest
    command: --api --docker
    ports:
      - "80:80"
      - "8089:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
