version: "3.7"
services:
  postgresql:
    image: "bitnami/postgresql:11"
    container_name: postgresql-master
    expose:
      - "5432"
    volumes:
      - "postgresql_master_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=postgresReplication
      - POSTGRESQL_USERNAME=user_go
      - POSTGRESQL_PASSWORD=1234
      - POSTGRESQL_DATABASE=mydb
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - postgres-replication
      - default

  postgresql-slave:
    image: "bitnami/postgresql:11"
    container_name: postgresql-slave
    expose:
      - "5432"
    volumes:
      - "postgresql_slave_data:/bitnami/postgresql"
    depends_on:
      - postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=postgresReplication
      - POSTGRESQL_MASTER_HOST=postgresql
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - postgres-replication

networks:
  postgres-replication:
    driver: bridge

volumes:
  postgresql_master_data:
    driver: local
  postgresql_slave_data:
    driver: local
